name: Dependencies

on:
    push:
        branches:
            - master
    pull_request:

env:
    PHP_VERSION: 7.2

jobs:
    composer-require-checker:
        name: Check missing composer requirements
        runs-on: ubuntu-18.04
        steps:
            -   uses: actions/checkout@v2
            -   name: Konfiguriere PHP-Version und -Einstellungen im Worker-Node
                uses: shivammathur/setup-php@v2
                with:
                  php-version: ${{ env.PHP_VERSION }}
                  tools: composer:v2
                  ini-values: variables_order=EGPCS
            -   name: Cache Composer Dependencies
                uses: actions/cache@v1
                with:
                    path: vendor/
                    key: composer-${{ env.PHP_VERSION }}-${{ hashFiles('composer.*') }}
                    restore-keys: |
                        composer-${{ env.PHP_VERSION }}-${{ github.ref }}
                        composer-${{ env.PHP_VERSION }}-
            -   run: |
                    composer install --no-interaction --no-scripts --no-progress --no-suggest
                    composer show
            -   name: ComposerRequireChecker
                uses: docker://webfactory/composer-require-checker:2.1.0
